=begin pod :kind("Type") :subkind("class") :category("exception")

=TITLE class X::Numeric::DivideByZero

=SUBTITLE Error while trying to divide by zero

    class X::Numeric::DivideByZero is Exception { }

Occurs when attempting to divide by zero.

For example:

    say 1 / 0;
    CATCH { default { put .^name, ': ', .Str } };
    # OUTPUT: «X::Numeric::DivideByZero: Attempt to divide by zero when coercing Rational to Str␤»

Note that the error is only thrown when you attempt to do something with the result. A simple

    1/0; # no Error

will only generate a silent Failure. It's the C<say> in the first example that triggers the exception.

=head1 Methods

=head2 method using

    method using()

If present, returns the name of the operator used, e.g. C<infix:<%%>>.

=head2 method details

    method details()

If present, contains some details on the operation that caused the failure.

=head2 method numerator

    method numerator()

If present, returns the numerator of the operation.

=end pod
